name: Fetch Darwin Linux
on:
  workflow_dispatch:
jobs:
  fetch-darwin-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch Darwin
        run: |
          make fetch.static.lib DIRECTORY=darwin-arm64 VERSION=v1.2.1 FILENAME=static-lib-osx-arm64
          make fetch.static.lib DIRECTORY=darwin-amd64 VERSION=v1.2.1 FILENAME=static-lib-osx-amd64
      - name: Fetch Linux
        run: |
          make fetch.static.lib DIRECTORY=linux-amd64 VERSION=v1.2.1 FILENAME=static-lib-linux-amd64
          make split.artefacts DIRECTORY=linux-amd64 FILETYPE=o
          make fetch.static.lib DIRECTORY=linux-arm64 VERSION=v1.2.1 FILENAME=static-lib-linux-arm64
          make split.artefacts DIRECTORY=linux-arm64 FILETYPE=o
        shell: bash
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: push darwin and linux libs
